# Generated by Django 4.2.4 on 2023-08-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contact_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
