# Generated by Django 4.2.4 on 2023-08-26 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_contact_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_approved',
        ),
    ]
