# Generated by Django 4.2.4 on 2023-08-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_contact_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
