# Generated by Django 4.2.4 on 2023-08-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('contact', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField()),
                ('guests', models.IntegerField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Booking Table',
            },
        ),
    ]
