# Generated by Django 4.2.4 on 2023-08-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_booking_table_date_alter_booking_table_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='date',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
