# Generated by Django 4.2.4 on 2023-08-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_booking_table_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
