# Generated by Django 4.2.4 on 2023-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_booking_table_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
