# Generated by Django 4.2.4 on 2023-08-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_booking_table_guests_alter_dish_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='iconimg',
            field=models.ImageField(default='', upload_to='icon'),
        ),
    ]
