# Generated by Django 4.2.4 on 2023-08-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='Sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_category'),
        ),
    ]
