# Generated by Django 4.2.4 on 2023-08-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_dish_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Sub_category',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.sub_category'),
        ),
    ]
