# Generated by Django 4.2.4 on 2023-08-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_dish_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub_category',
            new_name='SubCategory',
        ),
    ]
