# Generated by Django 4.2.4 on 2023-08-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_dish_sub_category_alter_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='Sub_category',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
