# Generated by Django 4.2.4 on 2023-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_sub_category_dish_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(null=True),
        ),
    ]
