# Generated by Django 4.2.4 on 2023-08-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='subicon',
            field=models.ImageField(default='', upload_to='subicon'),
        ),
    ]
